
FROM python:3.11-slim AS builder


LABEL maintainer="Igor Niemiec"


WORKDIR /app

RUN apt-get update && apt-get install -y build-essential


RUN python -m venv /app/venv

# Aktywacja środowiska wirtualnego i instalacja zależności
COPY requirements.txt .
RUN /app/venv/bin/pip install --no-cache-dir -r requirements.txt

COPY . .

ENV VISUAL_CROSSING_API_KEY=H93TEQFCKP7YYMVYGABJPAHLB


EXPOSE 8000


CMD ["/app/venv/bin/uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
