# Etap 1: Budowanie aplikacji
FROM node:20-alpine AS builder

LABEL maintainer="Igor Niemiec"


WORKDIR /app


ENV NODE_OPTIONS=--openssl-legacy-provider


COPY package.json package-lock.json ./
RUN npm install


COPY ./ ./


RUN npm run build


FROM nginx:alpine


RUN rm /etc/nginx/conf.d/default.conf


COPY nginx.conf /etc/nginx/conf.d


COPY --from=builder /app/build /usr/share/nginx/html


EXPOSE 80


CMD ["nginx", "-g", "daemon off;"]
